packages:
  - apps/*
  - packages/*
catalog:
  "@jest/globals": ^29.7.0
  "@mdx-js/loader": ^3.1.0
  "@mdx-js/react": ^3.1.0
  "@next/eslint-plugin-next": ^14.1.1
  "@next/mdx": ^15.0.2
  "@radix-ui/react-slot": ^1.0.2
  "@react-hook/window-scroll": ^1.3.0
  "@types/body-parser": ^1.19.5
  "@types/cors": ^2.8.17
  "@types/express": ^4.17.21
  "@types/mdx": ^2.0.13
  "@types/morgan": ^1.9.9
  "@types/node": ^20.11.24
  "@types/react": ^18.2.62
  "@types/react-dom": ^18.2.19
  "@types/supertest": ^6.0.2
  "@vercel/style-guide": ^5.2.0
  autoprefixer: ^10.4.20
  body-parser: ^1.20.2
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  cors: ^2.8.5
  embla-carousel-auto-scroll: ^8.3.1
  embla-carousel-react: ^8.3.1
  eslint-config-turbo: ^2.0.0
  eslint-plugin-mdx: ^3.1.5
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-storybook: ^0.8.0
  express: ^4.18.3
  gray-matter: ^4.0.3
  jest: ^29.7.0
  jest-environment-jsdom: ^29.7.0
  lucide-react: ^0.454.0
  morgan: ^1.10.0
  next: ^14.1.1
  postcss: ^8.4.47
  postcss-load-config: ^6
  prettier: ^3.2.5
  react: ^18.2.0
  react-dom: ^18.2.0
  remark-frontmatter: ^5.0.0
  remark-mdx-frontmatter: ^5.0.0
  supertest: ^6.3.4
  tailwind-merge: ^2.3.0
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  ts-jest: ^29.2.5
  tsup: ^8.0.2
  turbo: ^2.2.3
  typescript: 5.5.4
